Update 4 files
- /app/app.py
- /K8s/manifests/stock_analysis_app/deployment_stock.yml
- /K8s/manifests/monitoring/servicemonitor_app.yml
- /.gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,7 +6,7 @@ variables:
   ACCOUNT_ID: "$AWS_ACCOUNT_ID"
   DOCKER_IMAGE: "app_temoin"
   APP_INGRESS_NAME: ingress-stock-app
-  APP_VERSION: "1.0.2"
+  APP_VERSION: "1.0.3"
   OPENAI_TOKEN: "$OPENAI_TOKEN"
 
 stages:
@@ -18,58 +18,58 @@ stages:
   - destroy_infra
   - destroy_cluster
 
-# build-docker-image:
-#   stage: build
-#   image: 
-#     name: docker:24.0.5
-#   services:
-#     - docker:dind
-#   variables: 
-#     DOCKER_DRIVER: overlay2
-#     DOCKER_TLS_CERTDIR: ""
-#   before_script:
-#     # Connection to the gitlab Registry
-#     - echo "$PULL_PAT_TOKEN" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
-#     # Create a separate docker network for testing
-#     - docker network create test_env
-#   script:
-#     # Build a first test image
-#     # Unit tests are integrated into the Dockerfile build
-#     - docker build --target build -t $CI_REGISTRY/$DOCKER_IMAGE:test ./app
-#     # Run the container on the test network to copy the report.xml - Result report of the unit tests
-#     - docker run -d --name test_app_cont --hostname stock_analysis --network test_env -p 5000:5000 $CI_REGISTRY/$DOCKER_IMAGE:test
-#     # Wait for container to spin-up before attempting to copy the targeted content
-#     - sleep 5
-#     - docker cp test_app_cont:/app/report.xml $CI_PROJECT_DIR/report.xml
-#     # Remove useless container
-#     - docker rm -f test_app_cont
-#     # Build the release candidate image for Owasp testing
-#     - docker build --target production -t $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION ./app
-#     # Run the release candidate image for Owasp testing
-#     - docker run -d --name test_app_cont --hostname stock_analysis --network test_env -p 5000:5000 $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION
-#     # Make sure the rc container is up and running as expected
-#     - until docker run --network test_env --rm curlimages/curl curl http://stock_analysis:5000; do echo "Waiting for app to start..."; sleep 5; done
-#     # logout to pull image from public docker registry
-#     - docker logout
-#     # Run the owasp container with the automation framework symlinked to the stock_analysis_zap.yml template in repo
-#     - docker run --rm --name owaspzap --network test_env -v $(pwd):/zap/reports/:rw -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable bash -c "zap.sh -cmd -addonupdate; zap.sh -cmd -quickurl http://stock_analysis:5000 -autorun /zap/wrk/stock_analysis_zap.yml"
-#     # Login again to our Gitlab container registry to push the rc image there
-#     - echo "$PULL_PAT_TOKEN" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
-#     - docker push $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION
-#   tags:
-#     - build_job_docker
-#   artifacts:
-#     # Export the output as an artifact with 30 days retention, only viewable by dev on the project
-#     untracked: false
-#     when: on_success
-#     access: developer
-#     expire_in: 30 days
-#     name: "build_and_reports"
-#     paths:
-#       - ./app
-#       - combinedHtmlReport.html
-#       - report.xml
-#       - .docker/config.json
+build-docker-image:
+  stage: build
+  image: 
+    name: docker:24.0.5
+  services:
+    - docker:dind
+  variables: 
+    DOCKER_DRIVER: overlay2
+    DOCKER_TLS_CERTDIR: ""
+  before_script:
+    # Connection to the gitlab Registry
+    - echo "$PULL_PAT_TOKEN" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
+    # Create a separate docker network for testing
+    - docker network create test_env
+  script:
+    # Build a first test image
+    # Unit tests are integrated into the Dockerfile build
+    - docker build --target build -t $CI_REGISTRY/$DOCKER_IMAGE:test ./app
+    # Run the container on the test network to copy the report.xml - Result report of the unit tests
+    - docker run -d --name test_app_cont --hostname stock_analysis --network test_env -p 5000:5000 $CI_REGISTRY/$DOCKER_IMAGE:test
+    # Wait for container to spin-up before attempting to copy the targeted content
+    - sleep 5
+    - docker cp test_app_cont:/app/report.xml $CI_PROJECT_DIR/report.xml
+    # Remove useless container
+    - docker rm -f test_app_cont
+    # Build the release candidate image for Owasp testing
+    - docker build --target production -t $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION ./app
+    # Run the release candidate image for Owasp testing
+    - docker run -d --name test_app_cont --hostname stock_analysis --network test_env -p 5000:5000 $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION
+    # Make sure the rc container is up and running as expected
+    - until docker run --network test_env --rm curlimages/curl curl http://stock_analysis:5000; do echo "Waiting for app to start..."; sleep 5; done
+    # logout to pull image from public docker registry
+    - docker logout
+    # Run the owasp container with the automation framework symlinked to the stock_analysis_zap.yml template in repo
+    - docker run --rm --name owaspzap --network test_env -v $(pwd):/zap/reports/:rw -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable bash -c "zap.sh -cmd -addonupdate; zap.sh -cmd -quickurl http://stock_analysis:5000 -autorun /zap/wrk/stock_analysis_zap.yml"
+    # Login again to our Gitlab container registry to push the rc image there
+    - echo "$PULL_PAT_TOKEN" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin
+    - docker push $CI_REGISTRY/nevii/leverage-your-own-k8s-expert/$DOCKER_IMAGE:$APP_VERSION
+  tags:
+    - build_job_docker
+  artifacts:
+    # Export the output as an artifact with 30 days retention, only viewable by dev on the project
+    untracked: false
+    when: on_success
+    access: developer
+    expire_in: 30 days
+    name: "build_and_reports"
+    paths:
+      - ./app
+      - combinedHtmlReport.html
+      - report.xml
+      - .docker/config.json
 
 # deploy_eks:
 #   stage: deploy
@@ -187,99 +187,99 @@ stages:
 #       artifacts: true
 # #   # when: manual
 
-# deploy_stock_app:
-#   stage: provision
-#   image: registry.gitlab.com/nevii/terraform_eks/awsclitoolbox:v0.3
-#   before_script:
-#     # Install the necessary packages to use the exported yaml artifacts values in the files
-#     - pip install pyyaml
-#     - wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O /usr/local/bin/yq
-#     - chmod +x /usr/local/bin/yq
-#   script:
-#     # Set the cluster endpoint as target for kubectl commands
-#     - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
-#     # Use the artifact from build job to authenticate to the Gitlab container registry and pull the docker image built
-#     # The extracted values will be used to create a kubernetes secret
-#     - |
-#       cat <<EOF > gitlab_secret.yml
-#       apiVersion: v1
-#       kind: Secret
-#       metadata:
-#         name: gitlab-cred
-#         namespace: default
-#       data:
-#         .dockerconfigjson: $(cat .docker/config.json | base64 -w 0)
-#       type: kubernetes.io/dockerconfigjson
-#       EOF
-#     - kubectl create -f gitlab_secret.yml --dry-run=client -o yaml | kubectl apply -f -
-#     # Create a service in the cluster for communicating with the RDS instance
-#     # The rds dns adress extracted form the deploy db job will be used
-#     - |
-#       cat <<EOF > mysql-service.yml
-#       apiVersion: v1
-#       kind: Service
-#       metadata:
-#         labels:
-#           app: mysql-service
-#         name: mysql-service
-#       spec:
-#         externalName: $(yq eval '.rds_address.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml)
-#         selector:
-#           app: mysql-service
-#         type: ExternalName
-#       status:
-#         loadBalancer: {}
-#       EOF
-#     # Create a secret to be used for the app authentication toward the RDS instance
-#     # The values used will be extracted from the deploy db job
-#     - kubectl create -f mysql-service.yml --dry-run=client -o yaml | kubectl apply -f -
-#     - |
-#       cat <<EOF > db_secret.yml
-#       apiVersion: v1
-#       kind: Secret
-#       metadata:
-#         name: db-credentials
-#         namespace: default
-#       data:
-#         DB_USER: $(yq eval '.database_username.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
-#         DB_PASSWORD: $(yq eval '.database_password.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
-#         RDS_ADDRESS: $(yq eval '.rds_address.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
-#         DB_NAME: $(yq eval '.database_name.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
-#       EOF
-#     - kubectl create -f db_secret.yml --dry-run=client -o yaml | kubectl apply -f -
-#     # Deploy the application using a deployment manifest. A service and an Ingress are also defined 
-#     - kubectl create -f $CI_PROJECT_DIR/K8s/manifests/stock_analysis_app/deployment_stock.yml --dry-run=client -o yaml | kubectl apply -f -
-#     # Make sure the dns name is associated and the LB is up and running before extracting the dns adress into as environment variable into a file
-#     # Loop exits when non zero value is returned, retries every 10 secondes
-#     - |
-#       while [ -z "$LB_DNS" ]; do 
-#         echo "Waiting for Ingress to apply and return Load Balancer DNS name, retrying in 5 seconds..."
-#         sleep 5
-#         LB_DNS=$(kubectl get ingress ingress-stock-app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-#       done
-#     # Extract and store the ALB DNS adress value
-#     - LB_DNS=$(kubectl get ingress ingress-stock-app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-#     - echo "LB_DNS=$LB_DNS" > lb_dns.env
-#     # Make sure the key:value is correclty registered
-#     - cat lb_dns.env
-#   needs:
-#     # Job dependency, with artifact import enabled from them
-#     - job: deploy_db
-#       artifacts: true
-#     - job: build-docker-image
-#       artifacts: true
-#     # Export the output as an artifact with 1 day retention, only viewable by dev on the project
-#   artifacts:
-#     untracked: false
-#     when: on_success
-#     access: developer
-#     expire_in: 1 days
-#     paths:
-#       - $CI_PROJECT_DIR/lb_dns.env
-#   # Target the docker gitlab instance
-#   tags:
-#     - build_job_docker
-#   # when: manual
+deploy_stock_app:
+  stage: provision
+  image: registry.gitlab.com/nevii/terraform_eks/awsclitoolbox:v0.3
+  before_script:
+    # Install the necessary packages to use the exported yaml artifacts values in the files
+    - pip install pyyaml
+    - wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O /usr/local/bin/yq
+    - chmod +x /usr/local/bin/yq
+  script:
+    # Set the cluster endpoint as target for kubectl commands
+    - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
+    # Use the artifact from build job to authenticate to the Gitlab container registry and pull the docker image built
+    # The extracted values will be used to create a kubernetes secret
+    - |
+      cat <<EOF > gitlab_secret.yml
+      apiVersion: v1
+      kind: Secret
+      metadata:
+        name: gitlab-cred
+        namespace: default
+      data:
+        .dockerconfigjson: $(cat .docker/config.json | base64 -w 0)
+      type: kubernetes.io/dockerconfigjson
+      EOF
+    - kubectl create -f gitlab_secret.yml --dry-run=client -o yaml | kubectl apply -f -
+    # Create a service in the cluster for communicating with the RDS instance
+    # The rds dns adress extracted form the deploy db job will be used
+    - |
+      cat <<EOF > mysql-service.yml
+      apiVersion: v1
+      kind: Service
+      metadata:
+        labels:
+          app: mysql-service
+        name: mysql-service
+      spec:
+        externalName: $(yq eval '.rds_address.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml)
+        selector:
+          app: mysql-service
+        type: ExternalName
+      status:
+        loadBalancer: {}
+      EOF
+    # Create a secret to be used for the app authentication toward the RDS instance
+    # The values used will be extracted from the deploy db job
+    - kubectl create -f mysql-service.yml --dry-run=client -o yaml | kubectl apply -f -
+    - |
+      cat <<EOF > db_secret.yml
+      apiVersion: v1
+      kind: Secret
+      metadata:
+        name: db-credentials
+        namespace: default
+      data:
+        DB_USER: $(yq eval '.database_username.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
+        DB_PASSWORD: $(yq eval '.database_password.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
+        RDS_ADDRESS: $(yq eval '.rds_address.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
+        DB_NAME: $(yq eval '.database_name.value' $CI_PROJECT_DIR/Terraform_Infra/vars.yml | base64 -w 0)
+      EOF
+    - kubectl create -f db_secret.yml --dry-run=client -o yaml | kubectl apply -f -
+    # Deploy the application using a deployment manifest. A service and an Ingress are also defined 
+    - kubectl create -f $CI_PROJECT_DIR/K8s/manifests/stock_analysis_app/deployment_stock.yml --dry-run=client -o yaml | kubectl apply -f -
+    # Make sure the dns name is associated and the LB is up and running before extracting the dns adress into as environment variable into a file
+    # Loop exits when non zero value is returned, retries every 10 secondes
+    - |
+      while [ -z "$LB_DNS" ]; do 
+        echo "Waiting for Ingress to apply and return Load Balancer DNS name, retrying in 5 seconds..."
+        sleep 5
+        LB_DNS=$(kubectl get ingress ingress-stock-app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+      done
+    # Extract and store the ALB DNS adress value
+    - LB_DNS=$(kubectl get ingress ingress-stock-app -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+    - echo "LB_DNS=$LB_DNS" > lb_dns.env
+    # Make sure the key:value is correclty registered
+    - cat lb_dns.env
+  needs:
+    # Job dependency, with artifact import enabled from them
+    # - job: deploy_db
+    #   artifacts: true
+    - job: build-docker-image
+      artifacts: true
+    # Export the output as an artifact with 1 day retention, only viewable by dev on the project
+  artifacts:
+    untracked: false
+    when: on_success
+    access: developer
+    expire_in: 1 days
+    paths:
+      - $CI_PROJECT_DIR/lb_dns.env
+  # Target the docker gitlab instance
+  tags:
+    - build_job_docker
+  # when: manual
 
 monitoring:
   stage: monitor
@@ -294,14 +294,14 @@ monitoring:
     - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
     - helm list --all-namespaces
     # Add & Install the PrometheusxGrafana stack with Helm
-    - helm uninstall kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom || true
-    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
-    - helm repo update
+    # - helm uninstall kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom || true
+    # - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
+    # - helm repo update
     # - helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom --create-namespace -f $CI_PROJECT_DIR/K8s/manifests/monitoring/values.yml || true
     # - helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom -f $CI_PROJECT_DIR/K8s/manifests/monitoring/values.yml --reuse-values || true
     # - helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom || true
-    - helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom --create-namespace -f $CI_PROJECT_DIR/K8s/manifests/monitoring/values.yml || true
-    # - kubectl apply -f $CI_PROJECT_DIR/K8s/manifests/monitoring/servicemonitor_app.yml --dry-run=client -o yaml | kubectl apply -f -
+    # - helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitor-graf-prom --create-namespace -f $CI_PROJECT_DIR/K8s/manifests/monitoring/values.yml || true
+    - kubectl apply -f $CI_PROJECT_DIR/K8s/manifests/monitoring/servicemonitor_app.yml --dry-run=client -o yaml | kubectl apply -f -
     # - kubectl apply -f $CI_PROJECT_DIR/K8s/manifests/monitoring/podmonitor.yml --dry-run=client -o yaml | kubectl apply -f -
     # Target the docker gitlab instance
   tags:
@@ -309,7 +309,7 @@ monitoring:
   needs:
     # Job dependency
     # - deploy_eks
-    # - deploy_stock_app
+    - deploy_stock_app
 #   # when: manual
 
 # Job to run the load test using the DNS fetched in the previous job
